version: '3'
services:
  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_DB=exyutv_docker_v1
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=exyutv123
    ports:
      - 8000:5432
    networks:
      - exyutvnet

  rabbitMQ:
    image: rabbitmq:3-management
    container_name: 'rabbitmqcontainer'
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    ports:
      - 5672:5672
    expose:
      - 5672
    networks:
      - exyutvnet

  rabbitmq-service:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Iptv.Subscriber\Dockerfile
    environment:
      - RABBITMQ_HOST=rabbitMQ
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=iptv.blkn.app@gmail.com
      - SMTP_PASSWORD=reak ereo tsmn mlwz
      - ENABLE_SSL=true
      - MAIL_TIMEOUT=10000
      - MAIL_FROM_ADDRESS=no-replay@iptv.ba
      - MAIL_DISPLAY_NAME=iptv_blkn.ba
    depends_on:
      - rabbitMQ
      - postgres
    networks:
      - exyutvnet

  api:
    restart: unless-stopped
    build:
      context: .
      dockerfile: Iptv.Api\Dockerfile
    environment:
      - ConnectionStrings:"User ID=postgres;Password=exyutv123;Server=postgres;Port=5432;Database=exyutv_docker_v1;Integrated Security=true;Pooling=true"
      - RABBITMQ_HOST=rabbitMQ
      - RABBITMQ_PORT=5672
      - RABBITMQ_USERNAME=guest
      - RABBITMQ_PASSWORD=guest
      - SMTP_SERVER=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=iptv.blkn.app@gmail.com
      - SMTP_PASSWORD=reak ereo tsmn mlwz
      - ENABLE_SSL=true
      - MAIL_TIMEOUT=10000
      - MAIL_FROM_ADDRESS=no-replay@iptv.ba
      - MAIL_DISPLAY_NAME=iptv_blkn.ba
    ports:
      - 8080:80
    volumes:
      - ./wwwroot:/app/wwwroot
    networks:
      - exyutvnet
    depends_on:
      - postgres

networks:
  exyutvnet:
    driver: bridge
